version: '2'  
services:  

  rea:
    image: xtremxpert/docker-carra
    container_name: rea
    tty: true
    stdin_open: true
    environment:
    - DB_HOST=192.168.234.119
    - DB_NAME=rea_database
    - DB_PORT=5432
    - DB_USER=rea_user
    - DB_PASS=rea_pass
    - DEBUG=true
    ports:
      - "10000:8000"
