version: '2'  
services:  

  rea:
    image: xtremxpert/docker-carra
    container_name: rea
    tty: true
    stdin_open: true
    environment:
    - DB_HOST=db
    - DB_NAME=rea_database
    - DB_PORT=5432
    - DB_USER=rea_user
    - DB_PASS=rea_password
    ports:
      - "8000:8000"
