FROM python:3.5
ENV PYTHONUNBUFFERED 1


ENV APP_USER carra
ENV APP_ROOT /src

#---  Config as root 

RUN mkdir /config
COPY config /config
RUN pip install -r /config/requirements.txt

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         postgresql-client \
#     && rm -rf /var/lib/apt/lists/*


#--  User creation 
RUN groupadd -r ${APP_USER} 
RUN useradd -r -m -d ${APP_ROOT} -s /usr/sbin/nologin -g ${APP_USER} ${APP_USER} 


#-- Copy as User = $APP_USER  
WORKDIR ${APP_ROOT}
USER ${APP_USER}
COPY src /src
